version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "vitest",
    "mongo",
    "nodejs"
  ]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["/path"]